DocumentAppWeb/Models/ListItemVM.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace DocumentAppWeb.Models
{
    public class ListItemVM
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Author { get; set; }
        public string FileName { get; set; }

        [Display(Name = "Modified by")]
        public string ModifiedBy { get; set; }

        [Display(Name = "Created")]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd HH:mm}", ApplyFormatInEditMode = true)]
        public DateTime CreatedDate { get; set; }

        [Display(Name = "Modified")]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd HH:mm}", ApplyFormatInEditMode = true)]
        public DateTime ModifiedDate { get; set; }

        public string Path { get; set; }

        public string LibraryTitle { get; set; }

        public string ContentType { get; set; }

        public bool IsSharedWithGuest { get; set; }

        public string EditLink { get; set; }

        public string ViewLink { get; set; }

        public string Icon { get; set; }

        public string FullUrl { get; set; }

        public string FolderUrl { get; set; }
    }
}

DocumentAppWeb/Controllers/DocumentController.cs
using DocumentAppWeb.Models;
using DocumentAppWeb.Utils;
using Microsoft.SharePoint.Client;
using Microsoft.SharePoint.Client.Utilities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Configuration;
using System.Web.Mvc;

namespace DocumentAppWeb.Controllers
{
    public class DocumentController : Controller
    {
        public ActionResult SearchAllDocuments(string searchString, string libraryTitle)
        {
            using (var context = ContextProvider.CreateAppOnlyContext())
            {
                ViewBag.LibraryTitle = libraryTitle;
                var vm = DocumentHelper.GetAllDocumentsInLibrary(context, libraryTitle, searchString);
                return View("AllDocuments", vm);
            }
        }

        public ActionResult Search(string searchString, string libraryTitle)
        {
            using (var context = ContextProvider.CreateAppOnlyContext())
            {
                ViewBag.LibraryTitle = libraryTitle;
                var vm = DocumentHelper.GetSharedDocumentsInLibrary(context, libraryTitle, searchString);
                return View("SharedDocuments", vm);
            }
        }

        public ActionResult AllDocuments(string libraryTitle, string folderPath = null)
        {
            using (var context = ContextProvider.CreateAppOnlyContext())
            {
                ViewBag.LibraryTitle = libraryTitle;
                var vm = DocumentHelper.GetAllItemsInFolder(context, libraryTitle, folderPath);
                return View(vm);
            }
        }

        public ActionResult SharedDocuments(string libraryTitle, string folderPath)
        {
            using (var context = ContextProvider.CreateAppOnlyContext())
            {               
                ViewBag.LibraryTitle = libraryTitle;
                var vm = DocumentHelper.GetSharedItemsInFolder(context, libraryTitle, folderPath);
                return View(vm);
            }
        }

        public ActionResult AddLink(string url, string libraryTitle, string itemFolderUrl = null)
        {
            using (var context = ContextProvider.CreateAppOnlyContext())
            {             
                var link = DocumentHelper.AddGuestLink(context, url, true);

                return RedirectToAction("AllDocuments", new { libraryTitle = libraryTitle, folderPath = itemFolderUrl });
            }
        }

        public ActionResult DeleteLink(string url, string libraryTitle, string itemFolderUrl = null)
        {
            using (var context = ContextProvider.CreateAppOnlyContext())
            {
                DocumentHelper.DeleteGuestLink(context, url, true);

                return RedirectToAction("AllDocuments", new { libraryTitle = libraryTitle, folderPath = itemFolderUrl });
            }
        }

        [HttpPost]
        public PartialViewResult DeleteLink2(ListItemVM item)
        {
            using (var context = ContextProvider.CreateAppOnlyContext())
            {
                DocumentHelper.DeleteGuestLink(context, item.FullUrl, true);
                item.IsSharedWithGuest = false;
                item.EditLink = null;
                item.ViewLink = null;

                return PartialView("ListItemAdmin", item);
            }
        }
    }
}

DocumentAppWeb/Views/Document/AllDocuments.cshtml
@model IEnumerable<DocumentAppWeb.Models.ListItemVM>

@{
    ViewBag.Title = "All Documents";
}

<div class="panel panel-default">
    <div>
        <div class="panel-heading clearfix">
            <h3 class="panel-title pull-left">All Documents</h3>
            @using (Html.BeginForm("SearchAllDocuments", "Document", FormMethod.Get, new { @class = "navbar-form pull-right" }))
            {
                <div class="input-group">
                    <input type="hidden" name="SPHostUrl" value="@ViewBag.SPHostUrl" />
                    <input type="hidden" name="libraryTitle" value="@ViewBag.LibraryTitle" />
                    <input type="text" class="form-control" placeholder="Find a file" name="searchString" />
                    <span class="input-group-btn">
                        <button class="btn btn-primary" type="submit">
                            <i class="glyphicon glyphicon-search"></i>
                        </button>
                    </span>
                </div>
            }
        </div>
        <div class="panel-body">
            <table class="table">
                <thead>
                    <tr>
                        <th></th>
                        <th>@Html.DisplayNameFor(model => model.Name)</th>
                        <th>@Html.DisplayNameFor(model => model.Author)</th>
                        <th>@Html.DisplayNameFor(model => model.ModifiedBy)</th>
                        <th>@Html.DisplayNameFor(model => model.CreatedDate)</th>
                        <th>@Html.DisplayNameFor(model => model.ModifiedDate)</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        @Html.Partial("ListItemAdmin", item)
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>

DocumentAppWeb/Views/Document/Details.cshtml
@model IEnumerable<DocumentAppWeb.Models.Document>

@{
    ViewBag.Title = "Documents";
}

<div class="panel panel-default">
    <div class="panel-heading">Documents</div>

    <div class="panel-body">
        <table class="table table-striped">
            <tr>
                <th>@Html.DisplayNameFor(model => model.Name)</th>
                <th>@Html.DisplayNameFor(model => model.Author)</th>
                <th>@Html.DisplayNameFor(model => model.ModifiedBy)</th>
                <th>@Html.DisplayNameFor(model => model.CreatedDate)</th>
                <th>@Html.DisplayNameFor(model => model.ModifiedDate)</th>
            </tr>
            @foreach (var item in Model)
            {
                <tr>
                    <td>@Html.DisplayFor(modelItem => item.Name)</td>
                    <td>@Html.DisplayFor(modelItem => item.Author)</td>
                    <td>@Html.DisplayFor(modelItem => item.ModifiedBy)</td>
                    <td>@Html.DisplayFor(modelItem => item.CreatedDate)</td>
                    <td>@Html.DisplayFor(modelItem => item.ModifiedDate)</td>
                </tr>
            }
        </table>
    </div>
</div>

DocumentAppWeb/Views/Document/ListItem.cshtml
@model DocumentAppWeb.Models.ListItemVM

<tr>
    <td class="text-center"><img width="16" height="16" src="@Url.Content(Model.Icon)" title="@Model.FileName" /></td>
    @if (Model.IsSharedWithGuest)
    {
        <td><a href="@(Model.EditLink ?? Model.ViewLink)" target="_blank">@Model.Name</a></td>
    }
    else if (Model.ContentType == "Folder")
    {
        <td>
            @Html.ActionLink(Model.Name, "SharedDocuments", new { libraryTitle = Model.LibraryTitle, folderPath = Model.Path })
        </td>
    }
    else
    {
        <td>@Html.DisplayFor(modelItem => Model.Name)</td>
    }

    <td>@Html.DisplayFor(modelItem => Model.Author)</td>
    <td>@Html.DisplayFor(modelItem => Model.ModifiedBy)</td>
    <td>@Html.DisplayFor(modelItem => Model.CreatedDate)</td>
    <td>@Html.DisplayFor(modelItem => Model.ModifiedDate)</td>
</tr>

DocumentAppWeb/Views/Document/ListItemAdmin.cshtml
@model DocumentAppWeb.Models.ListItemVM

<tr id="@Model.Id">
    <td class="text-center"><img width="16" height="16" src="@Url.Content(Model.Icon)" title="@Model.FileName" /></td>
    @if (Model.IsSharedWithGuest)
    {
        <td><a href="@(Model.EditLink ?? Model.ViewLink)" target="_blank">@Model.Name</a></td>
    }
    else if (Model.ContentType == "Folder")
    {
        <td>
            @Html.ActionLink(Model.Name, "AllDocuments", new { libraryTitle = Model.LibraryTitle, folderPath = Model.Path })
        </td>
    }
    else
    {
        <td>@Html.DisplayFor(modelItem => Model.Name)</td>
    }

    <td>@Html.DisplayFor(modelItem => Model.Author)</td>
    <td>@Html.DisplayFor(modelItem => Model.ModifiedBy)</td>
    <td>@Html.DisplayFor(modelItem => Model.CreatedDate)</td>
    <td>@Html.DisplayFor(modelItem => Model.ModifiedDate)</td>
    <td>
        @if (Model.ContentType == "Document")
        {
            if (Model.IsSharedWithGuest)
            {
                <a href="@Url.Action("DeleteLink", "Document", new { url = Model.FullUrl, libraryTitle = ViewBag.LibraryTitle, itemFolderUrl = Model.FolderUrl })" class="btn" title="Remove link">
                    <i class="fa fa-chain-broken"></i>
                </a>

                @*@Ajax.ActionLink("Del", "DeleteLink2", new { item = Model }, 
                new AjaxOptions()
                {
                    HttpMethod = "POST",
                    AllowCache = false,
                    InsertionMode = InsertionMode.ReplaceWith,
                    UpdateTargetId = "" + Model.Id
                })*@
            }
            else
            {
                <a href="@Url.Action("AddLink", "Document", new { url = Model.FullUrl, libraryTitle = ViewBag.LibraryTitle, itemFolderUrl = Model.FolderUrl })" class="btn" title="Create link">
                    <i class="fa fa-chain"></i>
                </a>
            }
        }
    </td>
    <td>

    </td>
</tr>

DocumentAppWeb/Views/Document/SharedDocuments.cshtml
@model IEnumerable<DocumentAppWeb.Models.ListItemVM>

@{
    ViewBag.Title = "Shared Documents";
}

<div class="panel panel-default">
    <div>
        <div class="panel-heading clearfix">
            <h3 class="panel-title pull-left">Shared Documents</h3>
            @using (Html.BeginForm("Search", "Document", FormMethod.Get, new { @class = "navbar-form pull-right" }))
            {
                <div class="input-group">
                    <input type="hidden" name="SPHostUrl" value="@ViewBag.SPHostUrl" />
                    <input type="hidden" name="libraryTitle" value="@ViewBag.LibraryTitle" />
                    <input type="text" class="form-control" placeholder="Find a file" name="searchString" />
                    <span class="input-group-btn">
                        <button class="btn btn-primary" type="submit">
                            <i class="glyphicon glyphicon-search"></i>
                        </button>
                    </span>
                </div>
            }
        </div>
        <div class="panel-body">
            <table class="table">
                <thead>
                    <tr>
                        <th></th>
                        <th>@Html.DisplayNameFor(model => model.Name)</th>
                        <th>@Html.DisplayNameFor(model => model.Author)</th>
                        <th>@Html.DisplayNameFor(model => model.ModifiedBy)</th>
                        <th>@Html.DisplayNameFor(model => model.CreatedDate)</th>
                        <th>@Html.DisplayNameFor(model => model.ModifiedDate)</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        @Html.Partial("ListItem", item)
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>

DocumentAppWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Styles.Render("~/Content/fontawesome")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("DocumentApp", "SharedDocuments", "Document", new { area = "", libraryTitle = "Documents" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Shared Documents", "SharedDocuments", "Document", new { libraryTitle = "Documents" }, null)</li>
                    <li>@Html.ActionLink("All Documents", "AllDocuments", "Document", new { libraryTitle = "Documents" }, null)</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/spcontext")
    @RenderSection("scripts", required: false)
</body>
</html>